repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: (cibuildwheel/resources/pinned_docker_images.cfg)|(.svg$)
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.0
  hooks:
  - id: ruff
    args: ["--fix", "--show-fixes"]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.13.0
  hooks:
  - id: mypy
    name: mypy 3.8 on cibuildwheel/
    exclude: ^cibuildwheel/resources/.*py|bin/generate_schema.py$
    args: ["--python-version=3.8"]
    additional_dependencies: &mypy-dependencies
      - bracex
      - dependency-groups>=1.2
      - nox
      - orjson
      - packaging
      - pygithub
      - pytest
      - rich
      - tomli
      - tomli_w
      - types-certifi
      - types-click
      - types-jinja2
      - types-pyyaml
      - types-requests
      - types-setuptools
      - uv
      - validate-pyproject
  - id: mypy
    name: mypy 3.12
    exclude: ^cibuildwheel/resources/.*py$
    args: ["--python-version=3.12"]
    additional_dependencies: *mypy-dependencies

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck

- repo: local
  hooks:
  - id: disallow-caps
    name: Disallow improper capitalization
    language: pygrep
    entry: PyBind|Numpy|Cmake|Github|PyTest
    types:
    - markdown
    exclude: ^docs/working-examples\.md$  # Autogenerated
  - id: update-readme-changelog
    name: Update README changelog
    language: python
    entry: bin/update_readme_changelog.py
    files: ^docs/changelog.md$

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    args: ["-L", "sur,assertin", "-w"]
    exclude: ^docs/working-examples\.md$  # Autogenerated


- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.4
  hooks:
    - id: check-dependabot
    - id: check-github-actions
    - id: check-github-workflows
    - id: check-gitlab-ci
    - id: check-readthedocs
    - id: check-travis
    - id: check-jsonschema
      name: Check projects
      args: [--schemafile, docs/data/projects.schema.json]
      files: '^docs/data/projects.yml$'
    - id: check-metaschema
      files: '^docs/data/projects.schema.json$'
