repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: (cibuildwheel/resources/pinned_docker_images.cfg)|(.svg$)
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/asottile/pyupgrade
  rev: v2.21.0
  hooks:
  - id: pyupgrade
    name: PyUpgrade 3.6+
    args: ["--py36-plus"]
    exclude: ^bin/
  - id: pyupgrade
    name: PyUpgrade 3.7+ on bin
    exclude: ^(cibuildwheel|unit_test|test)/
    args: ["--py37-plus"]

- repo: https://github.com/PyCQA/isort
  rev: 5.9.2
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 21.6b0
  hooks:
  - id: black

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.17.0
  hooks:
  - id: setup-cfg-fmt
    stages: [manual]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    exclude: ^(bin|cibuildwheel/resources|docs)/.*py$
    args: ["--python-version=3.6", "--scripts-are-modules"]
    additional_dependencies:
      - packaging
      - types-jinja2
      - types-certifi
      - types-toml
  - id: mypy
    name: mypy 3.7+ on bin/
    files: ^((bin|docs)/.*py|noxfile.py)$
    args: ["--python-version=3.7", "--scripts-are-modules"]
    additional_dependencies:
      - packaging>=21.0
      - rich
      - types-jinja2
      - types-pyyaml
      - types-click
      - types-requests
      - types-toml

- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    exclude: cibuildwheel/resources/
    additional_dependencies: [flake8-bugbear]

- repo: local
  hooks:
  - id: disallow-caps
    name: Disallow improper capitalization
    language: pygrep
    entry: PyBind|Numpy|Cmake|Github|PyTest
    types:
    - markdown

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    args: ["-L", "sur"]
