repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: (cibuildwheel/resources/pinned_docker_images.cfg)|(.svg$)
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.12
  hooks:
  - id: ruff
    args: ["--fix", "--show-fixes"]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.16.0
  hooks:
  - id: mypy
    name: mypy 3.11 on cibuildwheel/
    args: ["--python-version=3.11"]
    additional_dependencies: &mypy-dependencies
      - bracex
      - dependency-groups>=1.2
      - nox>=2025.2.9
      - orjson
      - packaging
      - pygithub
      - pytest
      - rich
      - tomli
      - tomli_w
      - types-certifi
      - types-click
      - types-jinja2
      - types-pyyaml
      - types-requests
      - types-setuptools
      - uv
      - validate-pyproject
  - id: mypy
    name: mypy 3.13
    exclude: ^cibuildwheel/resources/.*py$
    args: ["--python-version=3.13"]
    additional_dependencies: *mypy-dependencies

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck

- repo: local
  hooks:
  - id: disallow-caps
    name: Disallow improper capitalization
    language: pygrep
    entry: PyBind|Numpy|Cmake|Github|PyTest
    types: [markdown]
    exclude: ^docs/working-examples\.md$  # Autogenerated
  - id: cog
    name: Cog the README
    language: python
    pass_filenames: false
    entry: cog -c -P -r -I ./bin README.md
    files: '^(README\.md|docs/changelog\.md|docs/options\.md|bin/readme.*)$'
    additional_dependencies: [cogapp]

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: ["-w"]
    exclude: ^docs/working-examples\.md$  # Autogenerated


- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.0
  hooks:
    - id: check-dependabot
    - id: check-github-actions
    - id: check-github-workflows
    - id: check-gitlab-ci
    # Disabled due to schema issue for now:
    # - id: check-readthedocs
    - id: check-travis
    - id: check-jsonschema
      name: Check projects
      args: [--schemafile, docs/data/projects.schema.json]
      files: '^docs/data/projects.yml$'
    - id: check-metaschema
      files: '^docs/data/projects.schema.json$'
