site_name: cibuildwheel
docs_dir: docs
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
      - yaml
repo_url: https://github.com/joerick/cibuildwheel

extra_css:
  - extra.css

extra_javascript:
  - extra.js

nav:
  - Home: index.md
  - setup.md
  - options.md
  - deliver-to-pypi.md
  - cpp_standards.md
  - faq.md
  - working-examples.md
  - contributing.md
  - changelog.md

markdown_extensions:
  - md_in_html
  - toc:
      permalink: True
  - attr_list
  - admonition
  - pymdownx.magiclink:
      repo_url_shortener: True
  - pymdownx.highlight:
      # use highlightjs - it's built-in to the theme
      use_pygments: False
  - pymdownx.superfences

plugins:
  - include-markdown
  - search
