site_name: cibuildwheel
docs_dir: docs
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
      - yaml
  collapse_navigation: false
  navigation_depth: 3
  custom_dir: docs/theme_overrides
repo_url: https://github.com/pypa/cibuildwheel
edit_uri: edit/main/docs/

extra_css:
  - extra.css

extra_javascript:
  - extra.js


nav:
  - Home: index.md
  - Guide:
    - setup.md
    - ci-services.md
    - deliver-to-pypi.md
    - faq.md
    - cpp_standards.md
  - Reference:
    - platforms.md
    - configuration.md
    - options.md
    - working-examples.md
  - About:
    - contributing.md
    - changelog.md

markdown_extensions:
  - md_in_html
  - toc:
      permalink: True
  - attr_list
  - admonition
  - pymdownx.magiclink:
      repo_url_shortener: True
  - pymdownx.highlight:
      # use highlightjs - it's built-in to the theme
      use_pygments: False
  - pymdownx.superfences

plugins:
  - include-markdown
  - search
  - macros:
      module_name: docs/main
      j2_variable_start_string: «
      j2_variable_end_string: »
      on_error_fail: true
      on_undefined: strict
