version: 2

jobs:
  osx-python3.9:
    macos:
      xcode: 12.5.1
    environment:
      PYTHON: python3
    steps:
      - checkout

      - run:
          name: Prepare the environment.
          command: bash .circleci/prepare.sh
      - run:
          name: Test.
          command: venv/bin/python ./bin/run_tests.py
          no_output_timeout: 30m

  linux-python3.9:
    docker:
      - image: circleci/python:3.9
    environment:
      PYTHON: python3
      # Temporarily restrict the tests that are run on CircleCI to prevent
      # test timeouts.
      PYTEST_ADDOPTS: -k "unit_test or main_tests or test_0_basic or test_docker_images"
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Prepare the environment.
          command: bash .circleci/prepare.sh
      - run:
          name: Test.
          command: venv/bin/python ./bin/run_tests.py
          no_output_timeout: 30m

  linux-aarch64:
    machine:
       image: ubuntu-2004:2022.04.1
    resource_class: arm.medium
    environment:
      PYTHON: python3
      # Temporarily restrict the tests that are run on CircleCI to prevent
      # test timeouts.
      PYTEST_ADDOPTS: -k "unit_test or main_tests or test_0_basic or test_docker_images"
    steps:
      - checkout

      - run:
          name: Prepare the environment.
          command: bash .circleci/prepare.sh
      - run:
          name: Test.
          command: venv/bin/python ./bin/run_tests.py
          no_output_timeout: 30m

workflows:
  version: 2
  all-tests:
    jobs:
      - osx-python3.9
      - linux-python3.9
      - linux-aarch64
