version: 2

jobs:
  osx-python3.6:
    macos:
      xcode: 12.5.1
    environment:
      PYTHON: python3
    steps:
      - checkout

      - run:
          name: Prepare the environment.
          command: bash .circleci/prepare.sh
      - run:
          name: Test.
          command: venv/bin/python ./bin/run_tests.py
          no_output_timeout: 30m

  linux-python3.6:
    docker:
      - image: circleci/python:3.6
    environment:
      PYTHON: python3
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Prepare the environment.
          command: bash .circleci/prepare.sh
      - run:
          name: Test.
          command: venv/bin/python ./bin/run_tests.py
          no_output_timeout: 30m

workflows:
  version: 2
  all-tests:
    jobs:
      - osx-python3.6
      - linux-python3.6
