name: Update dependencies

on:
  pull_request:
    paths:
      - '.github/workflows/update-dependencies.yml'
      - 'bin/update_pythons.py'
      - 'bin/update_docker.py'
      - 'bin/update_virtualenv.py'
      - 'bin/projects.py'
      - 'docs/data/projects.yml'
      - 'noxfile.py'
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # "At 06:00 on Monday."

jobs:
  update-dependencies:
    name: Update dependencies
    if: github.repository_owner == 'pypa' || github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: wntrblm/nox@2024.04.15
      with:
        python-versions: "3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13"

    - name: "Run update: dependencies"
      run: nox --force-color -s update_constraints
    - name: "Run update: python configs"
      run: nox --force-color -s update_pins
    - name: "Run update: docs user projects"
      run: nox --force-color -s update_proj -- --auth=${{ secrets.GITHUB_TOKEN }}

    # we use this step to grab a Github App auth token, so that PRs generated by this workflow
    # run the GHA tests.
    - uses: tibdex/github-app-token@v2
      id: generate-token
      if: github.ref == 'refs/heads/main' && github.repository == 'pypa/cibuildwheel'
      with:
        app_id: ${{ secrets.CIBUILDWHEEL_BOT_APP_ID }}
        private_key: ${{ secrets.CIBUILDWHEEL_BOT_APP_PRIVATE_KEY }}

    - name: Create Pull Request
      if: github.ref == 'refs/heads/main' && github.repository == 'pypa/cibuildwheel'
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Update dependencies
        title: '[Bot] Update dependencies'
        body: |
          Update the versions of our dependencies.

          PR generated by "Update dependencies" [workflow](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
        branch: update-dependencies-pr
        committer: "cibuildwheel-bot[bot] <83877280+cibuildwheel-bot[bot]@users.noreply.github.com>"
        author: "cibuildwheel-bot[bot] <83877280+cibuildwheel-bot[bot]@users.noreply.github.com>"
        token: ${{ steps.generate-token.outputs.token }}
        delete-branch: true
